// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Yami_SkipTitle","status":true,"description":"Skip the title scene for testing purpose.","parameters":{}},
{"name":"temp_CallDebug","status":true,"description":"CallDebug","parameters":{}},
{"name":"MK_MapScrollLimit","status":true,"description":"地图滚动限制 <MK_MapScrollLimit>","parameters":{"==== 游戏参数配置 ====":"","":"","==== 插件指令配置 ====":"","==== under ====":""}},
{"name":"MKP_BabaIsYou_Core","status":true,"description":"BabaIsYou复刻-核心 <MKP_BabaIsYou_Core>","parameters":{"---- 游戏参数配置 ----":"","":"","---- 插件指令配置 ----":"","---- 内容数据配置 ----":"","---- endline ----":""}},
{"name":"SAN_AnalogMove","status":false,"description":"アナログムーブ 3.1.5\r\nパーティキャラクターの移動をドット移動に変更します。","parameters":{}}
];
